package com.mobarenas.mavanity.menu;

/**
 * Created by HP1 on 12/22/2015.
 */
public enum ItemType {

    BACK, NAME, PET, REMOVE_PET, REMOVE_DISGUISE, REMOVE_HAT, DISGUISE, VIEWMODE, ARMOR, HAT,
    TOGGLE_PLAYERS, TOGGLE_PETS, TOGGLE_PARTICLES, TOGGLE_DISGUISES,
    REMOVE_HELMET, REMOVE_CHEST, REMOVE_LEGS, REMOVE_BOOTS, REMOVE_PARTICLE, PAGE_BACKWARD, PAGE_FORWARD,
    PARTICLE_PAGE, EFFECT_PAGE, PARTICLE, EFFECT,

}